modLoader="javafml"
loaderVersion="[40,)"
license="MIT License"
issueTrackerURL="https://github.com/MojangPlsFix/adventure-platform-forge/issues"

[[mods]]
modId="adventure_platform_forge"
version="${file.jarVersion}"
displayName="adventure-platform-fabric" #mandatory
#logoFile="examplemod.png" #optional
credits="KyoriPowered"
authors="MojangPlsFix" #optional
description='''
An adaptor for adventure to integrate with Fabric
'''

[[dependencies.adventure_platform_forge]]
    modId="forge" #mandatory
    mandatory=true #mandatory
    versionRange="[40,)" #mandatory
    ordering="NONE"
    side="BOTH"

[[dependencies.adventure_platform_forge]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.18.2,1.19)"
    ordering="NONE"
    side="BOTH"
